version: "3"

services:
   sonarr:
    networks:
     - Thera
     - Ares
    labels:
     - traefik.enable=true
     - traefik.http.routers.sonarr.middlewares=chain-authelia@file
     # Network to use
     - traefik.docker.network=Ares
     # Backend Name
     - traefik.backend=sonarr-svc
     # Router
     - traefik.http.routers.sonarr.entryPoints=https
     - traefik.http.routers.sonarr.rule=Host(`test.ares.systems`) && PathPrefix(`/sonarr`)
     - traefik.http.routers.sonarr.tls=true
     - traefik.http.services.sonarr.loadbalancer.server.port=8989
   radarr:
    networks:
     - Thera
     - Ares
    labels:
     - traefik.enable=true
     - traefik.http.routers.radarr.middlewares=chain-authelia@file
     # Network to use
     - traefik.docker.network=Ares
     # Backend Name
     - traefik.backend=radarr-svc
     # Router
     - traefik.http.routers.radarr.entryPoints=https
     - traefik.http.routers.radarr.rule=Host(`test.ares.systems`) && PathPrefix(`/radarr`) || Host(`og.ares.systems`) && PathPrefix(`/radarr`)
     - traefik.http.routers.radarr.tls=true
     - traefik.http.services.radarr.loadbalancer.server.port=7878
   jackett:
    networks:
     - Thera
     - Ares
    labels:
     - traefik.enable=true
     - traefik.http.routers.jackett.middlewares=chain-authelia@file
     # Network to use
     - traefik.docker.network=Ares
     # Backend Name
     - traefik.backend=jackett-svc
     # Router
     - traefik.http.routers.jackett.entryPoints=https
     - traefik.http.routers.jackett.rule=Host(`test.ares.systems`) && PathPrefix(`/jackett`)
     - traefik.http.routers.jackett.tls=true
     - traefik.http.services.jackett.loadbalancer.server.port=9117
   transmission:
    networks:
     - Thera
     - Ares
    labels:
     - traefik.enable=true
     - traefik.http.routers.transmission.middlewares=chain-authelia@file
     # Network to use
     - traefik.docker.network=Ares
     # Backend Name
     - traefik.backend=transmission-svc
     # Router
     - traefik.http.routers.transmission.entryPoints=https
     - traefik.http.routers.transmission.rule=Host(`test.ares.systems`) && PathPrefix(`/transmission`)
     - traefik.http.routers.transmission.tls=true
     - traefik.http.services.transmission-svc.loadbalancer.server.port=9091
networks:
    Thera:
     internal: true
    Ares:
     external: true